#!/bin/sh
#
# Creates Solaris packages
#
# $Id$
set -u

VERSION=0.8pre

PACKAGENAME=yapet-${VERSION}

SOLNAMECURSES=yapet-curses
SOLNAMECURSESv=${SOLNAMECURSES}-${VERSION}
SOLNAMENCURSES=yapet-ncurses
SOLNAMENCURSESv=${SOLNAMENCURSES}-${VERSION}

SOLPKGCURSES=GUENGEL-yapet-curses
SOLPKGCURSESv=${SOLPKGCURSES}-${VERSION}
SOLPKGNCURSES=GUENGEL-yapet-ncurses
SOLPKGNCURSESv=${SOLPKGNCURSES}-${VERSION}

PACKAGE=${PACKAGENAME}.tar.gz

TMPDIR=/var/tmp
URL=http://www.guengel.ch/yapet/downloads/${PACKAGE}
CC=cc
CXX=CC
CFLAGS='-g -xO0'
CXXFLAGS='-g -xO0'
PATH="/usr/bin:/usr/sbin:/usr/sfw/bin:/opt/sfw/bin:/usr/ccs/bin"
CURRENTUSER=`/usr/xpg4/bin/id -un`
export CC CXX CFLAGS CXXFLAGS PATH

mymsg() {
	cat <<EOF

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

$@

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

EOF
}

mydo() {
    for c in "$@"
    do
	mymsg "Doing $c"
	$c
	retval=$?
	if [ $retval -ne 0 ]
	then
	    echo "Command $c failed with status $retval"
	    exit 1
	fi
    done
}

cleanup () {
    mymsg "Cleaning up"
    curpwd=`pwd`
    cd ${TMPDIR}
    [ -f ${PACKAGE} ] && rm -f ${PACKAGE}
    [ -d ${PACKAGENAME} ] && rm -rf ${PACKAGENAME}
    [ -d ${SOLNAMECURSESv} ] && rm -rf ${SOLNAMECURSESv}
    [ -d ${SOLPKGCURSESv} ] && rm -rf ${SOLPKGCURSESv}
    [ -d ${SOLPKGCURSES} ] && rm -rf ${SOLPKGCURSES}
    [ -d ${SOLNAMENCURSESv} ] && rm -rf ${SOLNAMENCURSESv}
    [ -d ${SOLPKGNCURSESv} ] && rm -rf ${SOLPKGNCURSESv}
    [ -d ${SOLPKGNCURSES} ] && rm -rf ${SOLPKGNCURSES}
    [ -f ${SOLPKGCURSESv}.pkg ] && rm -f ${SOLPKGCURSESv}.pkg
    [ -f ${SOLPKGNCURSESv}.pkg ] && rm -f ${SOLPKGNCURSESv}.pkg
    cd ${curpwd}
}

cd ${TMPDIR}
cleanup

mymsg "Fetching yapet from ${URL}"
wget -O ${PACKAGE} ${URL}

#
# CURSES linked Package
#
LDFLAGS='-L/usr/sfw/lib -R/usr/sfw/lib'
CPPFLAGS='-I/usr/sfw/include'
export LDFLAGS CPPFLAGS

mymsg "Unpack $PACKAGE"
gtar xf $PACKAGE

mymsg "Moving ${PACKAGENAME} ${SOLNAMECURSESv}"
mv ${PACKAGENAME} ${SOLNAMECURSESv}
cd ${SOLNAMECURSESv}
mydo "./configure --prefix=/opt/guengel --mandir=/opt/guengel/man --without-libpth-prefix --without-libiconv-prefix --without-libintl-prefix" "dmake -j 10" "dmake -j 10 check" "make DESTDIR=${TMPDIR}/${SOLPKGCURSESv} install"

cd ${TMPDIR}/${SOLPKGCURSESv}
mkdir InfoFiles
cp ${TMPDIR}/${SOLNAMECURSESv}/LICENSE InfoFiles/copyright
mymsg "Creating pkginfo"
cat > InfoFiles/pkginfo <<EOF
ARCH=x86
CATEGORY=GUENGEL
NAME=${SOLNAMECURSES}
PKG=${SOLPKGCURSES}
VERSION=${VERSION}
BASEDIR=/opt
DESC=YAPET linked against System Curses
EMAIL=rafi@guengel.ch
EOF

mymsg "Creating depend"
cat > InfoFiles/depend <<EOF
I GUENGEL-yapet-ncurses  YAPET linked against NCURSES
P SUNWcsl                Core Solaris, (Shared Libs)
EOF

mymsg "Creating pkgproto"
pkgproto opt='' | sed -e "s/${CURRENTUSER} ${CURRENTUSER}/root bin/" > InfoFiles/prototype

cat >> InfoFiles/prototype <<EOF
i pkginfo
i depend
i copyright
EOF

cd InfoFiles
mymsg "Making package ${SOLPKGCURSESv}"
pkgmk -r ${TMPDIR}/${SOLPKGCURSESv} -d ${TMPDIR}

#
# NCURSES linked Package
#
cd ${TMPDIR}
LDFLAGS='-L/usr/sfw/lib -R/usr/sfw/lib -L/opt/sfw/lib -R/opt/sfw/lib'
CPPFLAGS='-I/usr/sfw/include -I/opt/sfw/include -I/opt/sfw/include/ncurses'
export LDFLAGS CPPFLAGS

mymsg "Unpack $PACKAGE"
gtar xf $PACKAGE

mymsg "Moving ${PACKAGENAME} ${SOLNAMENCURSESv}"
mv ${PACKAGENAME} ${SOLNAMENCURSESv}
cd ${SOLNAMENCURSESv}
mydo "./configure --prefix=/opt/guengel --mandir=/opt/guengel/man --without-libpth-prefix --without-libiconv-prefix --without-libintl-prefix" "dmake -j 10" "dmake -j 10 check" "make DESTDIR=${TMPDIR}/${SOLPKGNCURSESv} install"

cd ${TMPDIR}/${SOLPKGNCURSESv}
mkdir InfoFiles
cp ${TMPDIR}/${SOLNAMENCURSESv}/LICENSE InfoFiles/copyright
mymsg "Creating pkginfo"
cat > InfoFiles/pkginfo <<EOF
ARCH=x86
CATEGORY=GUENGEL
NAME=${SOLNAMENCURSES}
PKG=${SOLPKGNCURSES}
VERSION=${VERSION}
BASEDIR=/opt
DESC=YAPET linked against System Curses
EMAIL=rafi@guengel.ch
EOF

mymsg "Creating depend"
cat > InfoFiles/depend <<EOF
I GUENGEL-yapet-curses  YAPET linked against NCURSES
P SFWncur               ncurses - new curses library
EOF

mymsg "Creating pkgproto"
pkgproto opt='' | sed -e "s/${CURRENTUSER} ${CURRENTUSER}/root bin/" > InfoFiles/prototype

cat >> InfoFiles/prototype <<EOF
i pkginfo
i depend
i copyright
EOF

cd InfoFiles
mymsg "Making package ${SOLPKGCURSESv}"
pkgmk -r ${TMPDIR}/${SOLPKGNCURSESv} -d ${TMPDIR}

mymsg "Creating distributable packages"
cd ${TMPDIR}
[ -f ${SOLPKGCURSESv}.pkg.bz2 ] && rm -f ${SOLPKGCURSESv}.pkg.bz2
[ -f ${SOLPKGNCURSESv}.pkg.bz2 ] && rm -f ${SOLPKGNCURSESv}.pkg.bz2

pkgtrans -s . ${SOLPKGCURSESv}.pkg ${SOLPKGCURSES}
pkgtrans -s . ${SOLPKGNCURSESv}.pkg ${SOLPKGNCURSES}

mymsg "Compressing packages"
bzip2 -9 ${SOLPKGCURSESv}.pkg
bzip2 -9 ${SOLPKGNCURSESv}.pkg

cleanup
